# Generated by Django 5.2.5 on 2025-09-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
