# Generated by Django 5.2.6 on 2025-09-28 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id_city", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "city",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                ("id_day", models.AutoField(primary_key=True, serialize=False)),
                ("name_day", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "day",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Hour",
            fields=[
                ("id_hour", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "hour",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id_question", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=500)),
                ("image_question", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "question",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Questionary",
            fields=[
                ("id_questionary", models.AutoField(primary_key=True, serialize=False)),
                ("name_questionary", models.CharField(max_length=100)),
                ("Author", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "questionary",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                ("id_option", models.AutoField(primary_key=True, serialize=False)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="id_question",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.question",
                    ),
                ),
            ],
            options={
                "db_table": "option",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id_answer", models.AutoField(primary_key=True, serialize=False)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="id_question",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.question",
                    ),
                ),
            ],
            options={
                "db_table": "answer",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="question",
            name="questionary",
            field=models.ForeignKey(
                db_column="id_questionary",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.questionary",
            ),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id_recommendation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=800)),
                (
                    "total_percentage",
                    models.ForeignKey(
                        db_column="id_answer",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.answer",
                    ),
                ),
            ],
            options={
                "db_table": "recommendation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id_schedule", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day",
                    models.ForeignKey(
                        db_column="id_day",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.day",
                    ),
                ),
                (
                    "hour_aper",
                    models.ForeignKey(
                        db_column="id_hour_aper",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hour_aper",
                        to="api.hour",
                    ),
                ),
                (
                    "hour_close",
                    models.ForeignKey(
                        db_column="id_hour_close",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="hour_close",
                        to="api.hour",
                    ),
                ),
            ],
            options={
                "db_table": "schedule",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Optical",
            fields=[
                ("id_optical", models.AutoField(primary_key=True, serialize=False)),
                ("nameOp", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("tel", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=80, unique=True)),
                ("logo", models.CharField(max_length=600)),
                ("certCadecuacion", models.CharField(max_length=500)),
                ("certDispensacion", models.CharField(max_length=500)),
                (
                    "city",
                    models.ForeignKey(
                        db_column="id_city",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.city",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="id_schedule",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.schedule",
                    ),
                ),
            ],
            options={
                "db_table": "optical",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id_service", models.AutoField(primary_key=True, serialize=False)),
                ("name_service", models.CharField(max_length=300)),
                (
                    "optical",
                    models.ForeignKey(
                        db_column="id_optical",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.optical",
                    ),
                ),
            ],
            options={
                "db_table": "service",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id_test", models.AutoField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=500)),
                (
                    "questionary",
                    models.ForeignKey(
                        db_column="id_questionary",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.questionary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "test",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="test",
            field=models.ForeignKey(
                db_column="id_test",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.test",
            ),
        ),
    ]
