# Generated by Django 5.2.6 on 2025-09-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_city_day_hour_question_questionary_option_answer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id_comment", models.AutoField(primary_key=True, serialize=False)),
                (
                    "optical",
                    models.ForeignKey(
                        db_column="id_optical",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.optical",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        db_column="id_state",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.state",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment",
                "managed": True,
            },
        ),
    ]
