# Generated by Django 5.2.6 on 2025-09-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="role",
            table="role",
        ),
        migrations.AlterModelTable(
            name="state",
            table="state",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
