# Generated by Django 5.2.5 on 2025-10-06 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_hour_hour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optical",
            name="schedule",
        ),
        migrations.AddField(
            model_name="schedule",
            name="optical",
            field=models.ForeignKey(
                blank=True,
                db_column="id_optical",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.optical",
            ),
        ),
        migrations.AlterField(
            model_name="optical",
            name="view",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
