# Generated by Django 5.2.5 on 2025-10-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_option_descriptionop"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionary",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
