# Generated by Django 5.2.6 on 2025-10-16 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                db_column="id_question",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="options",
                to="api.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="questionary",
            field=models.ForeignKey(
                db_column="id_questionary",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="questions",
                to="api.questionary",
            ),
        ),
    ]
