# Generated by Django 5.2.6 on 2025-10-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_option_question_alter_question_questionary"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="correct",
            field=models.BooleanField(default=False),
        ),
    ]
