# Generated by Django 5.2.6 on 2025-10-17 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_option_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="date_test",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
