# Generated by Django 5.2.6 on 2025-10-18 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_test_date_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalogue",
            fields=[
                ("id_catalogue", models.AutoField(primary_key=True, serialize=False)),
                ("nameP", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=300)),
                (
                    "optical",
                    models.ForeignKey(
                        db_column="id_optical",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.optical",
                    ),
                ),
            ],
            options={
                "db_table": "catalogue",
                "managed": True,
            },
        ),
    ]
