# Generated by Django 5.2.6 on 2025-10-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_catalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="description",
            field=models.CharField(default="Sin descripción", max_length=500),
        ),
        migrations.AddField(
            model_name="catalogue",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
