# Generated by Django 5.2.6 on 2025-10-20 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_catalogue_description_catalogue_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="source",
            field=models.ForeignKey(
                db_column="source",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.option",
            ),
        ),
    ]
