# Generated by Django 5.2.6 on 2025-10-20 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_test_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="question",
            field=models.ForeignKey(
                db_column="id_question",
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.question",
            ),
        ),
    ]
