# Generated by Django 5.2.6 on 2025-10-20 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_test_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_comment",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.state",
            ),
        ),
    ]
