# Generated by Django 5.2.6 on 2025-10-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_comment_date_comment_alter_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="descriptionC",
            field=models.CharField(default="No hay descripcion", max_length=500),
        ),
    ]
