# Generated by Django 5.2.6 on 2025-10-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_comment_descriptionc"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="score",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
