# Generated by Django 5.2.6 on 2025-10-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_comment_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="optical",
            name="descriptionOp",
            field=models.CharField(default="No hay descripción", max_length=600),
        ),
    ]
