# Generated by Django 5.2.6 on 2025-10-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_optical_logo_alter_question_image_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="total_percentage",
        ),
        migrations.RemoveField(
            model_name="option",
            name="correct",
        ),
        migrations.RemoveField(
            model_name="test",
            name="source",
        ),
        migrations.AddField(
            model_name="option",
            name="value",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="test",
            name="answer",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalogue/image/"
            ),
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
