# Generated by Django 5.2.6 on 2025-10-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_remove_recommendation_total_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optical",
            name="certCadecuacion",
            field=models.FileField(
                blank=True, null=True, upload_to="optical/certCadecuacion/"
            ),
        ),
        migrations.AlterField(
            model_name="optical",
            name="certDispensacion",
            field=models.FileField(
                blank=True, null=True, upload_to="optical/certDispensacion/"
            ),
        ),
    ]
