# Generated by Django 5.2.7 on 2025-10-22 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_optical_certcadecuacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to="api.role"
            ),
        ),
    ]
