# Generated by Django 5.2.6 on 2025-10-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_product_alter_catalogue_namep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="answer",
            field=models.ForeignKey(
                db_column="id_option",
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.option",
            ),
        ),
    ]
