# Generated by Django 5.2.7 on 2025-10-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_test_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogue",
            name="optical",
            field=models.ForeignKey(
                db_column="id_optical",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.optical",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="optical",
            field=models.ForeignKey(
                blank=True,
                db_column="id_optical",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.optical",
            ),
        ),
    ]
