# Generated by Django 5.2.6 on 2025-11-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_catalogue_optical_alter_schedule_optical"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified_owner",
            field=models.BooleanField(default=False),
        ),
    ]
