# Generated by Django 5.2.6 on 2025-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_user_is_verified_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="optical",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
